name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:       # allows to trigger manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes